### ISSUE TITLE
BuildError in Heroku

### ISSUE THREAD

**Issue by send2cloud** [begriffs/lucre#8]
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.2.4
-----> Installing dependencies using bundler 1.13.6
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/........
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Installing multi_json 1.7.2
       Installing i18n 0.6.1
       Installing rake 10.0.4
       Installing builder 3.0.4
       Installing journey 1.0.4
       Installing erubis 2.7.0
       Installing hike 1.2.2
       Installing tilt 1.3.7
       Installing rack 1.4.5
       Installing mime-types 1.22
       Installing polyglot 0.3.3
       Installing arel 3.0.2
       Installing coffee-script-source 1.6.2
       Installing tzinfo 0.3.37
       Installing json 1.7.7 with native extensions
       Installing thor 0.18.1
       Installing pg 0.17.1 with native extensions
       Using bundler 1.13.6
       Installing sass 3.2.7
       Installing execjs 1.4.0
       Installing rest-client 1.6.7
       Installing activesupport 3.2.13
       Installing treetop 1.4.12
       Installing rack-cache 1.2
       Installing rack-test 0.6.2
       Installing sprockets 2.2.2
       Installing rack-ssl 1.3.4
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       /tmp/build_321996cffed203345efc86bc97a5fb0c/send2cloud-lucre-9b81ef2/vendor/ruby-2.2.4/bin/ruby
       -r ./siteconf20161116-225-g56vxu.rb extconf.rb
       creating Makefile
       make "DESTDIR=" clean
       make "DESTDIR="
       compiling generator.c
       In file included from generator.c:1:0:
       ../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
       ../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but
       only 1 given
       VALUE result = rb_str_new(FBUFFER_PAIR(fb));
       ^
       ../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer
       without a cast [enabled by default]
       VALUE result = rb_str_new(FBUFFER_PAIR(fb));
       ^
       make: *** [generator.o] Error 1
       make failed, exit code 2
       Gem files will remain installed in
       /tmp/build_321996cffed203345efc86bc97a5fb0c/send2cloud-lucre-9b81ef2/vendor/bundle/ruby/2.2.0/gems/json-1.7.7
       for inspection.
       Results logged to
       /tmp/build_321996cffed203345efc86bc97a5fb0c/send2cloud-lucre-9b81ef2/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/json-1.7.7/gem_make.out
       An error occurred while installing json (1.7.7), and Bundler cannot continue.
       Make sure that `gem install json -v '1.7.7'` succeeds before bundling.
       Bundler Output: Fetching gem metadata from https://rubygems.org/........
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Installing multi_json 1.7.2
       Installing i18n 0.6.1
       Installing rake 10.0.4
       Installing builder 3.0.4
       Installing journey 1.0.4
       Installing erubis 2.7.0
       Installing hike 1.2.2
       Installing tilt 1.3.7
       Installing rack 1.4.5
       Installing mime-types 1.22
       Installing polyglot 0.3.3
       Installing arel 3.0.2
       Installing coffee-script-source 1.6.2
       Installing tzinfo 0.3.37
       Installing json 1.7.7 with native extensions
       Installing thor 0.18.1
       Installing pg 0.17.1 with native extensions
       Using bundler 1.13.6
       Installing sass 3.2.7
       Installing execjs 1.4.0
       Installing rest-client 1.6.7
       Installing activesupport 3.2.13
       Installing treetop 1.4.12
       Installing rack-cache 1.2
       Installing rack-test 0.6.2
       Installing sprockets 2.2.2
       Installing rack-ssl 1.3.4
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       
       /tmp/build_321996cffed203345efc86bc97a5fb0c/send2cloud-lucre-9b81ef2/vendor/ruby-2.2.4/bin/ruby
       -r ./siteconf20161116-225-g56vxu.rb extconf.rb
       creating Makefile
       
       make "DESTDIR=" clean
       
       make "DESTDIR="
       compiling generator.c
       In file included from generator.c:1:0:
       ../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
       ../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but
       only 1 given
       VALUE result = rb_str_new(FBUFFER_PAIR(fb));
       ^
       ../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer
       without a cast [enabled by default]
       VALUE result = rb_str_new(FBUFFER_PAIR(fb));
       ^
       make: *** [generator.o] Error 1
       
       make failed, exit code 2
       
       Gem files will remain installed in
       /tmp/build_321996cffed203345efc86bc97a5fb0c/send2cloud-lucre-9b81ef2/vendor/bundle/ruby/2.2.0/gems/json-1.7.7
       for inspection.
       Results logged to
       /tmp/build_321996cffed203345efc86bc97a5fb0c/send2cloud-lucre-9b81ef2/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/json-1.7.7/gem_make.out
       
       An error occurred while installing json (1.7.7), and Bundler cannot continue.
       Make sure that `gem install json -v '1.7.7'` succeeds before bundling.
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by begriffs** [comment]
Thanks for reporting this. I opened a pull request to fix this. Could you try deploying from that branch? If it works for you I'll merge it.

**Comment by send2cloud** [comment]
I am new to git - so I'll try to follow along... :)
![image](https://cloud.githubusercontent.com/assets/2567775/21252384/33fe667e-c30b-11e6-8287-fdb40fc4dd13.png)

I can only fork from the main branch (from 4yrs) - not sure how to fork your new fixed branch (as it is not merged yet)  - 
Tried searching here:
http://stackoverflow.com/questions/6743514/how-can-i-fetch-an-unmerged-pull-request-for-a-branch-i-dont-own

**Comment by begriffs** [comment]
Excellent, I'll merge. Thanks again for reporting, and also for testing my change.
